### ISSUE TITLE
Buggy Model Import

### ISSUE THREAD

**Issue by 1manfactory** [leozide/leocad#226] opened 2018-04-12 10:00 UTC
Windows
LeoCAD 18.02

I tried to import a model generated with LDRAW http://omr.ldraw.org/file/603

The result was not so nice. (See picture)

![unbenannt](https://user-images.githubusercontent.com/232674/38670456-1aa22bce-3e49-11e8-80ab-0f66ec50665b.JPG)

**Comment by leozide** [comment] 2018-04-13 21:33
I think this is a duplicate of #215, the model loads correctly for me.

**Closed by leozide** 2018-04-13 21:33 UTC
