### ISSUE TITLE
BUG: CRITICAL - Parts list crash

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#435] opened 2020-01-12 17:26 UTC
Hi Leo,

Been using the latest build and happen to have experienced a reproducible crash when browsing throught the parts list items under the technic section.

It reaches a segment and then closes cold turkey.

Steps:

Open Leocad,
Open Model,
Open submodel entry for edit,
Select 'Technic' from parts list,
Scroll down into parts preview

[CRASH]

Thank you for looking into it

**Comment by leozide** [comment] 2020-01-12 18:13
I can't repro the crash, can you get me a callstack?

**Comment by nathaneltitane** [comment] 2020-01-12 18:13
@leozide running kde via kubuntu - how can i grab it?

**Comment by leozide** [comment] 2020-01-12 18:16
Probably the easiest way is from QtCreator. Either launch from there or Attach from the Debug Menu.

**Comment by nathaneltitane** [comment] 2020-01-12 18:26
Might be related to the unnofficial library - i was able to reproduce the crash with other categories - let me try without it.

**Comment by nathaneltitane** [comment] 2020-01-12 18:41
@leozide counterpart of this bug: adding the unofficial folder into the ldraw archive ends up in leocad not reading the unofficial folder or detecting it within the archive.

should it be placed at the same top-level as the archive?

**Comment by nathaneltitane** [comment] 2020-01-15 17:54
UPDATE:

reproducible by using ldrawunf.zip for unofficial parts:

Scrolling into the technic section will crash the application

![image](https://user-images.githubusercontent.com/5674757/72458064-e3d0fb00-3795-11ea-8a1d-97557305b85f.png)

Sending you the dump file by email @leozide

**Comment by leozide** [comment] 2020-01-15 19:35
I don't get a crash, did you modify either complete.zip of ldrawunf.zip?

**Comment by nathaneltitane** [comment] 2020-01-15 19:38
no, but i can redownload them to see?

**Comment by Symbian9** [comment] 2020-01-17 06:59
I also has a crash when fast switched from one category to another and try immediately scroll list of parts.

Seems like this is some memory leaks on generating icons, because there newer such crush if set "No Icons" in list/palette preferences.

> I don't get a crash, did you modify either `complete.zip` of `ldrawunf.zip`?

I suggest this does not matter, because I got crash also when only `complete.zip` used.

**Comment by leozide** [comment] 2020-01-17 22:54
I've checked in a crash fix, see if it helps you.

**Comment by Symbian9** [comment] 2020-01-19 06:46
> I've checked in a crash fix, see if it helps you

Nope. Just tested `LeoCAD-Linux-5895744-x86_64.AppImage` — it still crash on quick switching between parts categories and fast list scrolling.

**Comment by leozide** [comment] 2020-01-20 03:02
I can't find anything else, can you run from gdb and get a call stack?

**Comment by Symbian9** [comment] 2020-01-20 03:14
> I can't find anything else, can you run from gdb and get a call stack?

Here is my log:

```
$ gdb ./LeoCAD-Linux-ddf6f9d-x86_64.AppImage
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./LeoCAD-Linux-ddf6f9d-x86_64.AppImage...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/user/AppImages/LeoCAD/LeoCAD-Linux-ddf6f9d-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 13570]
process 13566 is executing new program: /tmp/.mount_LeoCADj29P4j/usr/bin/leocad
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecc74700 (LWP 13576)]
[New Thread 0x7fffe783e700 (LWP 13577)]
[New Thread 0x7fffe5b20700 (LWP 13578)]
[New Thread 0x7fffd7fff700 (LWP 13579)]
[New Thread 0x7fffcffff700 (LWP 13580)]
malloc(): corrupted top size

Thread 1 "AppRun" received signal SIGABRT, Aborted.
0x00007ffff643c7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)
```

**Comment by leozide** [comment] 2020-01-20 03:23
You need to type bt to print it, but that doesn’t have symbols so you need to compile yourself.

**Comment by Symbian9** [comment] 2020-01-20 04:57
> that doesn’t have symbols so you need to compile yourself.

I can't do it myself.

Could you build custom AppImage with symbols and provide it for me using `transfer.sh`?

- https://transfer.sh

**Comment by Symbian9** [comment] 2020-01-20 05:24
@leocad, I may try `18.02` release build (with debug symbols) provided by @pbartfai

- https://download.opensuse.org/repositories/home:/cabelo/Debian_10/amd64/

Would be it usable for this case?

**Comment by leozide** [comment] 2020-01-20 17:25
that would probably work, just remember to type bt in gdb

**Comment by Symbian9** [comment] 2020-01-24 06:32
> that would probably work, just remember to type bt in gdb

OK, just reproduced & here it is

```
$ gdb leocad
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from leocad...Reading symbols from /usr/lib/debug/.build-id/23/9e6918390e5f702c77fc8fb7a4e1fb64c47576.debug...done.
done.
(gdb) run
Starting program: /usr/bin/leocad 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee06c700 (LWP 587)]
[New Thread 0x7fffe6962700 (LWP 588)]
[New Thread 0x7fffe4d2d700 (LWP 589)]
[New Thread 0x7fffd75ff700 (LWP 590)]
[New Thread 0x7fffd6dfe700 (LWP 591)]
malloc(): corrupted top size

Thread 1 "leocad" received signal SIGABRT, Aborted.
0x00007ffff649a7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff649a7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6485535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff64dc508 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff64e2c1a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff64e620d in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff64e673b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff64e785a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007ffff64e8dc8 in posix_memalign () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007fffe4f78cf5 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r300_dri.so
#9  0x00007fffe538e556 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r300_dri.so
#10 0x00007fffe523d55c in ?? () from /usr/lib/x86_64-linux-gnu/dri/r300_dri.so
#11 0x00007fffe523f888 in ?? () from /usr/lib/x86_64-linux-gnu/dri/r300_dri.so
#12 0x00005555555e8ba7 in lcContext::CreateVertexBuffer (this=this@entry=0x555556a4b760, 
    Size=117264, Data=Data@entry=0x555557d2f3a0) at common/lc_context.cpp:735
#13 0x00005555555edba5 in lcPiecesLibrary::UpdateBuffers (this=0x555555949ac0, 
    Context=0x555556a4b760) at common/lc_library.cpp:1461
#14 0x00005555556335ce in lcScene::Draw (this=this@entry=0x7fffe8001e00, Context=0x555556a4b760)
    at common/lc_application.h:82
#15 0x00005555555a3171 in View::OnDraw (this=0x7fffe8001d70) at common/view.cpp:832
#16 0x00007ffff7d5d71b in QGLWidget::glDraw() () from /lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#17 0x00007ffff7d5d06d in QGLWidget::paintEvent(QPaintEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5OpenGL.so.5
#18 0x00007ffff780a4d8 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff77cc4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff77d3970 in QApplication::notify(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#21 0x00007ffff6c664f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff78030ca in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff7803987 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff77d9ca3 in QWidgetPrivate::repaint_sys(QRegion const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff77f2964 in QWidgetPrivate::syncBackingStore() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff780a608 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff77cc4c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff77d3970 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff6c664f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff6c694db in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6cb8173 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff5d1af2e in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff5d1b1c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff5d1b25c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff6cb7797 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007fffef3e4401 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#37 0x00007ffff6c651cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007ffff6c6d1a2 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x000055555559877e in main (argc=<optimized out>, argv=<optimized out>) at qt/qtmain.cpp:185
(gdb)
```

**Comment by leozide** [comment] 2020-01-24 21:14
That's a little more helpful. Can you try the latest change please?

**Closed** 2021-01-29 23:38 UTC
