### ISSUE TITLE
Moving a copied and pasted piece generates empty steps at end of timeline

### ISSUE THREAD

**Issue by j6t** [leozide/leocad#36] opened 2017-03-07 22:43 UTC
When a piece is copied to the clipboard, then pasted, than moved to a later step, then the next Save operation inserts empty steps at the end of the timeline.

To reproduce, open this file: [TestStepsInserted.ldr.txt](https://github.com/leozide/leocad/files/826040/TestStepsInserted.ldr.txt) (remove the .txt extension). Then:

1. Switch to the timeline panel.
2. Select the blue piece in Step 1.
3. Hit Ctrl+C, then Ctrl+V. A new blue piece is inserted in Step 1.
4. Drag the *new* (now selected) piece and drop it over Step 9 or the piece in Step 9 in such a way that it is inserted at the last position of the timeline.
5. Save under a new file name with File->Save As.
6. File->New
7. File->1 (the file save under item 5 above).

Notice that there are now empty steps 10 to 17 in the timeline. This is not expected because the steps were not present when the file was saved.

**Comment by leozide** [comment] 2017-03-08 01:13
This is the same bug as the other one you reported, the correct fix will take a little bit of work.

**Comment by nathaneltitane** [comment] 2017-03-08 05:23
Can a duplicate part feature be created that alleviates the copy/paste method?

Duplicating would serve as an in-place copy/paste that would insert the selected part directly after its original rather than inside a new step or at the end of the parts list of a given step.

**Comment by leozide** [comment] 2017-03-08 05:57
The bug is caused by dragging a piece in the timeline, it happens without copying and pasting. I could put in a 2 line fix for this but it won't solve the real issue, which I believe is also the cause of duplicate text in ldr files that someone else had reported on the old bug database and I could never reproduce.

With that said, I can add a clone command as well.

**Comment by j6t** [comment] 2017-03-08 06:40
@nathaneltitane Copy and paste currently works like you describe your "duplicate piece" function: The pasted piece is inserted in the same step as the original. It is not inserted in a new step or the current step. I wish the latter would be the case.

**Comment by nathaneltitane** [comment] 2017-03-08 16:41
@leozide true, and I'm sorry for forgetting it was doing so, though the duplication would be different in the sense that it copies and pastes the part *directly after* its original rather than at the end of the step.

could that be implemented?

Rationale:

Model editing and updating could benefit in place edits that would not require reorganizing stepping and parts order every time there'S a modification.

**Comment by leozide** [comment] 2017-03-08 23:59
I've added a duplicate/clone action, ctrl+d by default.

**Comment by j6t** [comment] 2017-03-09 06:52
Thanks. Now Paste could insert at the end of the timeline like the Insert operation does, no?

**Closed** 2017-03-19 00:43 UTC
