### ISSUE TITLE
Recognize external parts (.dat) located in same folder

### ISSUE THREAD

**Issue by Symbian9** [leozide/leocad#305] opened 2019-02-28 07:25 UTC
If there are DAT-files in same folder where opened LDR/MPD file located, recognize it as external parts.

**Comment by leozide** [comment] 2019-02-28 23:51
I don't understand this bug, how is this different than the previous one you wrote about datsville?

**Comment by Symbian9** [comment] 2019-03-01 00:05
This is not a bug report for Datsville.

Here I mean that need add option for LeoCAD recognize DAT-files stored in same directory where opened LDR/MPD file placed (no matter, if opened LDR/MPD files include those DAT files or not)

**Comment by leozide** [comment] 2019-03-01 00:14
Then I believe this is also a duplicate of #181.

**Closed by leozide** 2019-03-01 00:14 UTC
