### ISSUE TITLE
export to HTML on Mac says "Error creating images"

### ISSUE THREAD

**Issue by chicks-net** [leozide/leocad#255] opened 2018-09-03 18:57 UTC
I'm on a Mac.  OSX 10.11.6.  LeoCAD 18.02.  I do an export to HTML, pick a folder, keep the default options and I get a dialog box with

> Error creating images.

When I do a render I also get no resulting files.

Do I need additional software installed for these features to work?

**Comment by leozide** [comment] 2018-09-04 21:09
No, you don't need anything extra. I just tested and saving images is working for me.
Are you trying to save really high resolution images?
Can you post the contents of the About LeoCAD dialog?

**Comment by Symbian9** [comment] 2018-09-04 21:12
It could be some issue with permission for writing files into folder.

**Comment by chicks-net** [comment] 2018-09-04 21:16
It is able to create the HTML files and the images for the parts, but not the image for the model.  So I don't think permissions are an issue.  I'll add the About dialog when I get home to the Mac.

**Comment by leozide** [comment] 2018-09-04 22:26
Try saving a 100x100 image to see if size is the problem.

**Comment by chicks-net** [comment] 2018-09-05 18:01
# LeoCAD about

![screen shot 2018-09-03 at 11 53 03](https://user-images.githubusercontent.com/1099609/45111608-3b6b4b00-b0fa-11e8-9232-be27def356b5.png)

# Error message

![screen shot 2018-09-03 at 11 52 50](https://user-images.githubusercontent.com/1099609/45111648-59d14680-b0fa-11e8-98d0-245081ef60c4.png)

# export dialog

![screen shot 2018-09-05 at 11 00 14](https://user-images.githubusercontent.com/1099609/45111847-e67c0480-b0fa-11e8-8668-6e2db3e02ed8.png)

I retried this with the 100x100 as requested and I'm getting the same error message.  This is also right after a fresh reboot of the Mac.

# Before and after directory:

```
$ ls -al
total 0
drwxr-xr-x   2 chicks  staff    68 Sep  5 10:58 .
drwx------+ 32 chicks  staff  1088 Sep  5 10:58 ..
$ ls -l
total 104
-rw-r--r--  1 chicks  staff   2890 Sep  5 10:58 3006.dat.png
-rw-r--r--  1 chicks  staff   3707 Sep  5 10:58 3031.dat.png
-rw-r--r--  1 chicks  staff   3450 Sep  5 10:58 3035.dat.png
-rw-r--r--  1 chicks  staff    231 Sep  5 10:58 Pyramid 28H-01.html
-rw-r--r--  1 chicks  staff    274 Sep  5 10:58 Pyramid 28H-02.html
-rw-r--r--  1 chicks  staff    285 Sep  5 10:58 Pyramid 28H-03.html
-rw-r--r--  1 chicks  staff  20509 Sep  5 10:58 Pyramid 28H-parts.png
-rw-r--r--  1 chicks  staff    203 Sep  5 10:58 Pyramid 28H-pieces.html
```

**Comment by leozide** [comment] 2018-09-05 22:57
I've had problems with Intel HD GPUs before, I'll try to find something to test on.

Do you have anti-aliasing enabled in your options (View Menu->Preferences->Rendering tab)? If so, can you try disabling and seeing if it works?

**Comment by chicks-net** [comment] 2018-09-06 02:27
It was already disabled.

![screen shot 2018-09-05 at 19 25 35](https://user-images.githubusercontent.com/1099609/45131395-a7bd6d00-b141-11e8-9d4c-33b5bf5a6561.png)

**Comment by chicks-net** [comment] 2018-09-08 04:50
I ran into the same issue on Linux.  I tried the 18.02 AppImage on CentOS 7 with all of the updates installed.  I'm attaching [my project](https://github.com/leozide/leocad/files/2363007/Pyramid.zip)
 in case that is the source of the problem.

It was interesting to me that in this case the parts used image was generated, but not the images for the steps.  I am able to get the same error when I do File -> Save Image.

I'm going to be on the road for the next week so my ability to test things will be limited, but I am happy to help out where I can.  Are there any debug logs buried somewhere?

**Comment by leozide** [comment] 2018-09-09 17:08
I think this is a duplicate of #196.

I tested my development build (on Windows) and it works fine, but 18.02 it doesn't save images. Can you try setting AA to 2x and seeing if it works for you?

**Comment by chicks-net** [comment] 2018-09-16 20:04
Sorry it took so long for me to respond, but my trip was more all-consuming than I hoped for. ⛰ 

That fixed it!  Switching AA to 2x let me render the images.  I've been able to render up to 1280x1280 with no trouble. 😃 

Is there any further debugging I could do on Mac or Linux that would help others avoid this?

**Comment by leozide** [comment] 2018-09-17 17:57
I think this bug is fixed, I just need to release a new version. I've been busy this year and haven't had much time to work on the app, but I should be able to update before the end of the year.

**Closed by leozide** 2018-09-17 17:57 UTC
