### ISSUE TITLE
Feature request: FPS camera controls

### ISSUE THREAD

**Issue by mjhorvath** [leozide/leocad#443] opened 2020-02-02 17:32 UTC
I would like to request a new camera mode.

If you play video games you may be familiar with the FPS genre. FPS stands for "first-person shooter". Usually these types of games use the WASD keys and mouse to move the player around. W is forward, B is back, A is left and D is right. All movement is parallel to the ground plane. You use the mouse to point the camera in various directions, but all movement remains parallel to the ground plane.

I would like to request this type of camera mode. I have a large model of a town and this sort of camera would make it easier for me to move the camera around in this context. It would improve my workflow.

Thanks.

**Comment by mjhorvath** [comment] 2020-02-02 17:35
If Leonardo is not familiar with this video game genre, can anyone recommend a free video game he can use to learn what it is and how it works?

**Comment by nathaneltitane** [comment] 2020-02-02 18:26
@mjhorvath @leozide this is another element that would bind well with the request in #428

**Comment by leozide** [comment] 2020-02-03 21:53
> If Leonardo is not familiar with this video game genre, can anyone recommend a free video game he can use to learn what the type of camera is and how it works?

I know what FPS games are

**Comment by hendursaga** [comment] 2022-01-01 20:38
> [C]an anyone recommend a free video game he can use to learn what the type of camera is and how it works?

No need for a video game, [Blender 3D](https://www.blender.org/) has nice 'FPS' camera functionality..

**Comment by Lewiscowles1986** [comment] 2022-01-01 21:34
This is a duplicate of #165 as mentioned by @hendursaga https://github.com/leozide/leocad/issues/165#issuecomment-1003616439

**Comment by leozide** [comment] 2022-01-03 20:14
Closing the duplicate bug.

**Closed by leozide** 2022-01-03 20:14 UTC

**Comment by nathaneltitane** [comment] 2022-02-01 19:04
![image](https://user-images.githubusercontent.com/5674757/152033897-3fbad4de-6d50-43e1-8c23-cbaf1c042311.png)
